export default {
    title: {
        display: 'flex',
        alignItems: 'center',
        textDecoration: 'underline',
        textShadow: '5px 5px 5px',
        backgroundColor: 'rgba(0,0,0,0.5)',
        borderRadius: 15,
        borderColor: '#5f5f5f',
        borderBottomColor: '#555555',
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 5,
        borderBottomStyle: 'dotted',
        boxShadow: '5px 5px 5px #555555',
        color: '#555555',
        cursor: 'move',
        fontSize: 15,
        fontWeight: 'bold',
        fontStyle: 'italic',
        lineHeight: '15px',
        margin: 5,
        maxHeight: 50,
        minWidth: 50,
        opacity: 0.5,
        padding: 5
    },

    button: {
        textAlign: 'center',
        textDecoration: 'underline',
        textShadow: '5px 5px 5px',
        backgroundColor: 'rgba(0,0,0,0.5)',
        borderRadius: 15,
        borderColor: '#5f5f5f',
        borderBottomColor: '#555555',
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 5,
        borderBottomStyle: 'dotted',
        boxShadow: '5px 5px 5px #555555',
        color: '#555555',
        cursor: 'move',
        fontSize: 15,
        fontWeight: 'bold',
        fontStyle: 'italic',
        lineHeight: '15px',
        margin: 5,
        maxHeight: 50,
        minWidth: 50,
        opacity: 0.5,
        padding: 5
    },
    input: {
        textAlign: 'center',
        textDecoration: 'underline',
        textShadow: '5px 5px 5px',
        backgroundColor: 'rgba(0,0,0,0.5)',
        borderRadius: 15,
        borderColor: '#5f5f5f',
        borderBottomColor: '#555555',
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 5,
        borderBottomStyle: 'dotted',
        boxShadow: '5px 5px 5px #555555',
        color: '#555555',
        cursor: 'move',
        fontSize: 15,
        fontWeight: 'bold',
        fontStyle: 'italic',
        lineHeight: '15px',
        margin: 5,
        maxHeight: 50,
        minWidth: 50,
        opacity: 0.5,
        padding: 5
    },
    label: {
        textAlign: 'center',
        textDecoration: 'underline',
        textShadow: '5px 5px 5px',
        backgroundColor: 'rgba(0,0,0,0.5)',
        borderRadius: 15,
        borderColor: '#5f5f5f',
        borderBottomColor: '#555555',
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 5,
        borderBottomStyle: 'dotted',
        boxShadow: '5px 5px 5px #555555',
        color: '#555555',
        cursor: 'move',
        fontSize: 15,
        fontWeight: 'bold',
        fontStyle: 'italic',
        lineHeight: '15px',
        margin: 5,
        maxHeight: 50,
        minWidth: 50,
        opacity: 0.5,
        padding: 5
    }
};